site_name: SlideShow.digital
site_description: Documentation for Slideshow - Digital Signage System
copyright: Copyright © 2025 Milan Fabian
theme:
  name: material
  custom_dir: overrides
  favicon: assets/favicon.ico
  logo: assets/logo.svg
  palette:
    scheme: slate
  features:
    - search.suggest
    - navigation.top
    - navigation.tracking   
    - navigation.tabs
    - navigation.indexes
    
plugins:
  - mkdocs-video
  - search
  - minify:
      minify_html: true
      
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - attr_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCJFSXCItojY4PS76JNr_pdQ
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/slideshowPlay
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/SlideshowPlay
    - icon: fontawesome/solid/mug-hot
      link: https://ko-fi.com/slideshow
  generator: false

extra_css:
  - assets/extra.css
  
nav:
  - Home: index.md
  - Get started: 
    - get-started/index.md
    - get-started/tutorial.md
    - get-started/white-label.md
  - Documentation:
    - documentation/index.md
    - Playback:
      - documentation/playback/supported-media-types.md
      - Video playback:
        - documentation/playback/video-playback/index.md
        - documentation/playback/video-playback/4k-videos.md
      - documentation/playback/web-pages.md
      - documentation/playback/synchronized-playback.md
      - documentation/playback/background-audio.md
      - Special content:
        - documentation/playback/special-content/weather-forecast.md
        - documentation/playback/special-content/rss-feeds.md
        - documentation/playback/special-content/date-time.md
        - documentation/playback/special-content/android-widgets.md
        - documentation/playback/special-content/name-days.md
        - documentation/playback/special-content/video-stream.md
        - documentation/playback/special-content/video-input.md
        - documentation/playback/special-content/audio-stream.md
      - On-screen formatting:
        - documentation/playback/on-screen-formatting/transitions-animations.md
        - documentation/playback/on-screen-formatting/scaling-images.md
        - documentation/playback/on-screen-formatting/fonts.md
        - documentation/playback/on-screen-formatting/description-text.md
    - Network access:
      - documentation/network-access/web-interface.md
      - documentation/network-access/file-upload.md
      - File synchronization:
        - documentation/network-access/file-synchronization/index.md
        - Google Drive: documentation/network-access/file-synchronization/file-synchronization-google-drive.md
        - Dropbox: documentation/network-access/file-synchronization/file-synchronization-dropbox.md
        - HTTP / FTP: documentation/network-access/file-synchronization/file-synchronization-http-ftp.md
      - documentation/network-access/communication-between-devices.md
      - documentation/network-access/management-multiple-players.md
    - Configuration:
      - Playback configuration:
        - documentation/configuration/playback-configuration/content-playlist.md
        - Screen layout:
          - documentation/configuration/playback-configuration/screen-layout/index.md
          - documentation/configuration/playback-configuration/screen-layout/inspiration-for-layouts.md
        - documentation/configuration/playback-configuration/layout-playlist-scheduling.md
        - documentation/configuration/playback-configuration/scheduled-file-deletion.md
      - documentation/configuration/file-storage.md
      - documentation/configuration/settings.md
      - documentation/configuration/automatic-startup.md
      - documentation/configuration/screen-rotation.md
      - documentation/configuration/remote-update.md
      - documentation/configuration/localization.md
      - documentation/configuration/setup-csv.md
      - Backup and restore: documentation/configuration/configuration-backup-restore.md
    - Interactivity:
      - documentation/interactivity/keyboard.md
      - documentation/interactivity/triggers.md
      - documentation/interactivity/face-detection.md
    - Integration:
      - documentation/integration/rest-api.md
      - documentation/integration/serial-port.md
      - documentation/integration/local-javascript-api.md
      - documentation/integration/mqtt.md
      - documentation/integration/open-sound-control.md
    - Hardware:
      - documentation/hardware/suggested-hardware.md
      - documentation/hardware/benchmarks.md
      - documentation/hardware/root-on-android.md
      - Hardware reviews:
        - documentation/hardware/hardware-reviews/amazon-fire-tv-stick-4k-max.md
        - documentation/hardware/hardware-reviews/mekotronics-r58x.md
        - documentation/hardware/hardware-reviews/benq-st550k.md
        - documentation/hardware/hardware-reviews/novastar-tb40.md
        - documentation/hardware/hardware-reviews/intel-compute-stick.md
    - Case studies:
      - documentation/case-studies/art-hotel-kastiel.md
      - documentation/case-studies/artwork-james-mcgrath.md
      - documentation/case-studies/local-business-patriots.md
      - documentation/case-studies/ormiston-horizon-academy.md
    - documentation/release-notes.md
    - documentation/troubleshooting.md
    - documentation/support-us.md
    - documentation/privacy-policy.md
  - Contact us: contact-us/index.md
    